import './globals.css'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Providers } from './components/Providers/Providers.server'
import { Navbar } from './components/Navbar'
import { Footer } from './components/Footer/Footer'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// RainbowKitCssHotfix = https://github.com/rainbow-me/rainbowkit/issues/1546
const RainbowKitCssHotfix =
  '[&>[data-rk]]:flex [&>[data-rk]]:flex-col [&>[data-rk]]:h-full'

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex h-full min-h-screen flex-col antialiased ${RainbowKitCssHotfix}`}
      >
        <Providers>
          <Navbar />
          <main className="mx-auto w-full max-w-3xl grow py-4">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
